line-length = 120
exclude = [
    "anri/sandbox",
    "docs/",
    # "tests/"
    "scripts/release_notes.py",
    "scripts/prepare_changelog.py"
]

[lint]
extend-select = [
    "D",
    "N",
    "F841",
    "ANN",
]
ignore = [
    "N806",  # allow uppercase variable names
]

[lint.per-file-ignores]
"tests/*" = ["D", "ANN"]  # Ignore "D" (Docstrings) in the tests folder
"__init__.py" = ["F401"] # Ignore unused imports in init files

[lint.pydocstyle]
convention = "numpy"
ignore-decorators = []
property-decorators = []